import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import FloatingNav from "@/components/layout/FloatingNav";
import { AmbientBackground } from "@/components/layout/AmbientBackground";

const serif = Noto_Serif_JP({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["200", "300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${serif.variable} text-primary antialiased`}>
        <AmbientBackground />
        <FloatingNav />
        <main className="relative z-10 min-h-screen flex flex-col">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
