import type { Metadata } from "next";
import { Zen_Old_Mincho } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import FloatingNav from "@/components/layout/FloatingNav";

const serif = Zen_Old_Mincho({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${serif.variable} bg-void text-primary antialiased`}>
        <main className="relative z-10 min-h-screen flex flex-col">
          {children}
          <Footer />
        </main>
        <FloatingNav />
        <div className="fixed inset-0 z-50 pointer-events-none opacity-20 bg-[url('/noise.svg')] mix-blend-overlay"></div>
      </body>
    </html>
  );
}
